#
# application.yml — главный конфигурационный файл Spring Boot.
#
#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.
#

server:
  port: 8080 # Default server port

#logging:
#  level:
#    org:
#      springframework: DEBUG
#  logging.level.org.hibernate=DEBUG

spring:
  liquibase:
    default-schema: public # Default database schema
    url: jdbc:postgresql://localhost:5432/postgres # JDBC URL (if not using primary datasource)
    user: postgres # Database user (if not using primary datasource)
    password: postgres # Database password (if not using primary datasource)
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
#    maximumPoolSize: 5
    jpa:
      hibernate:
        ddl-auto: update # Automatically update schema
        show-sql: true # Log SQL statements
token:
  signing:
    key: 122B6C396F39E6A8754DC7428433EF1F7B76AA135C417B842E0BA83B67
springdoc:
  api-docs:
    path: /api-docs
swagger-ui:
  url: "http://localhost:8080/swagger-ui/index.html"